server:
  port: 8082
  servlet:
    context-path: /
# DataSource Config
spring:
  servlet:
    multipart:
      # 上传单个文件大小
      max-file-size: 10MB
      # 一次请求大小
      max-request-size: 100MB
  datasource:
#    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema-h2.sql
#    data: classpath:db/data-h2.sql
#    url: jdbc:h2:mem:test
#    username: root
#    password: test

    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bloodwar?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #连接池的配置信息
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化，最小，最大连接数
      initial-size: 3
      min-idle: 3
      max-active: 18
      # 获取数据库连接等待的超时时间
      max-wait: 60000
      # 配置多久进行一次检测，检测需要关闭的空闲连接 单位毫秒
      time-between-eviction-runs-millis: 60000
      test-while-idle: true
      validation-query: SELECT 1
  freemarker:
    allow-request-override: false
    cache: false
    check-template-location: true
    charset: UTF-8
    content-type: text/html; charset=utf-8
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/
    settings:
      template_update_delay: 10
      locale: zh_CN
      datetime_format: yyyy-MM-dd HH:mm:ss
      date_format: yyyy-MM-dd
      number_format: '#.##'
  resources:
    chain:
      strategy:
        content:
          paths: /css/**,/js/**,/img/**
          enabled: false
    static-locations:
    - "classpath:/META-INF/resources/"
    - "classpath:/resources/"
    - "classpath:/static/"
    - "classpath:/public/"
    - "file:/Volumes/小眼神/APMServ5.2.6/www/htdocs/"
mybatis-plus:
  mapper-locations: classpath*:com/lgren/rxsg/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: com.lgren.rxsg.entity
  #自动使用枚举
#  type-enums-package: com.lgren.rxsg.entity.enums
  global-config:
    db-config:
      logic-delete-value: 1
      #主键类型  0:"数据库ID自增", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
    #刷新mapper 调试神器
    refresh: true
logging:
  level:
    com.lgren.rxsg.mapper: debug